#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="Shortcuts to handle local dev env"
SUBCOMMAND_HELP=$(cat <<EOH

init                  Init, configure the local dev environment;
                      and start the app.
                      
start                 Start transervicos in local dev environment.

stop [SERVER]         Stop transervicos in local dev environment. 

clean_data            Clean all data in local dev environment.

db_migrate            Run DB migration.

goto                  Open transervicos app in localhost. 
                      Will trigger 'open URL', in OSX this
                      will fire up your browser.

EOH
)

function start() {
  error "not implemented."
}

function init() {
  error "not implemented."
}

function stop() {
  error "not implemented."
}

function clean_db_data() {
  error "not implemented."
}

function goto() {
  error "not implemented."
}

function db_migrate() {
  error "not implemented."
}

is_help_mode "${@}" && return

case ${1} in
  start)
    start
    ;;
  init)
    init
    ;;
  stop)
    stop
    ;;
  clean_data)
    clean_db_data
    ;;
  db_migrate)
    db_migrate
    ;;
  goto)
    goto
    ;;
esac