#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="Shortcuts to handle local dev env"
SUBCOMMAND_HELP=$(cat <<EOH

init                  Init, configure the local dev environment;
                      and start the app.
                      
start                 Start transervicos in local dev environment.

stop [SERVER]         Stop transervicos in local dev environment. 

clean_data            Clean all data in local dev environment.

db_migrate            Run DB migration.

goto                  Open transervicos app in localhost. 
                      Will trigger 'open URL', in OSX this
                      will fire up your browser.

EOH
)

function start() {
  docker-compose start
}

function init() {
  docker-compose up --build -d
  docker-compose run web /bin/bash -c "rake db:create && rake db:migrate"
}

function stop() {
  docker-compose stop
}

function clean_db_data() {
  error "not implemented."
}

function goto() {
  error "not implemented."
}

function db_migrate() {
  error "not implemented."
}

function checkin_dance() {
  STATUS="$(git status -s)"
  [[ -n "${STATUS}" ]] && error "'Comite' as alterações antes de continuar"
  git pull -r
  docker-compose run web /bin/bash -c "rspec spec && rubocop"
  [[ $? != 0 ]] && error "Falha executando os testes"
  echo "Verifique o status do CI. Está verde?"
  read "is_green"
  [[ "$is_green" == y ]] && git push || echo "Por favor conserte antes de continuar"
}

is_help_mode "${@}" && return

case ${1} in
  start)
    start
    ;;
  init)
    init
    ;;
  stop)
    stop
    ;;
  clean_data)
    clean_db_data
    ;;
  db_migrate)
    db_migrate
    ;;
  goto)
    goto
    ;;
  dance)
    checkin_dance
    ;;
esac