#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="Shortcuts to handle the project setup"
SUBCOMMAND_HELP=$(cat <<EOH

check           Check all required software.

install         Install all required and not 
                installed software.

EOH
)

function check_setup() {
  error "not implemented."
}

function install_all() {
  error "not implemented."
}

is_help_mode "${@}" && return

case ${1} in
  check)
    check_setup
    ;;
  install)
    install_all
  ;;
esac
