#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="Run application tests"
SUBCOMMAND_HELP=$(cat <<EOH

all           Run all application tests. Including
              static analysis.

style         Run static analysis for Ruby
              with Rubocop.

EOH
)

function all() {
  docker-compose run web bash -c "rubocop && rspec spec"
}

function style() {
  docker-compose run web bash -c "rubocop"
}

is_help_mode "${@}" && return

case ${1} in
  all)
    all
    ;;
  style)
    style
    ;;
esac