#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="Shortcuts to run tests"
SUBCOMMAND_HELP=$(cat <<EOH

unit          Run all unit tests.

all           Run all application tests. Including
              static analysis.

style         Run static analysis for Ruby
              with Rubocop.


EOH
)

function run_all() {
  # Run all should run both rubocop and unit tests
  error "not implemented"
}

function run_rubocop() {
  #Rubocop is Ruby's static code analyzer and code formatter. To run rubocop, you need to run the following command: "rspec spec"
  error "not implemented"
}

function run_unit() {
  #to run the unit tests you need to run the following command: "rspec spec"
  error "not implemented"
}

is_help_mode "${@}" && return

case ${1} in
  unit)
    run_unit
    ;;
  all)
    run_all
    ;;
  style)
    run_rubocop
    ;;
esac