#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="List relevant URLs"
SUBCOMMAND_HELP=$(cat <<EOH

all             List all URLs and aliases.

goto [ALIAS]    Will trigger 'open URL', in OSX this
                will fire up your browser.

show [ALIAS]    List URL for an specific [ALIAS].

[ALIAS]         Just a shortcut. Same as 'show [ALIAS]'.

EOH
)

declare -A "list"
list[dev]='http://localhost:3000'
list[ci]='https://gitlab.com/juuh42dias/transervicos/pipelines'

function _show_all() {
    in_cyan "Listing all URLs:"
    # echo ${list[@]} | xargs -n 1 echo
    
    printf "%-20s %s\n" "ALIAS" "URL"
    for name in "${!list[@]}"; do
        printf "%-20s %s\n" ${name} ${list[${name}]}
    done
}

function _show_url_for() {
    local alias=${1}
    [[ -n "${alias}" ]] && echo ${list[${alias}]} || _show_all
}

function _goto() {
    error "not implemented"
}

is_help_mode "${@}" && return

case ${1} in
    goto)
        _goto ${2}
    ;;
    all)
        _show_all
    ;;
    show)
        _show_url_for ${2}
    ;;
    *)
        _show_url_for ${1}
    ;;
esac