#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="List relevant URLs"
SUBCOMMAND_HELP=$(cat <<EOH

all             List all URLs and aliases.

goto [ALIAS]    Will trigger 'open URL', in OSX this
                will fire up your browser.

show [ALIAS]    List URL for an specific [ALIAS].

[ALIAS]         Just a shortcut. Same as 'show [ALIAS]'.

EOH
)

declare -A "list"

function _show_all() {
  error "not implemented"
}

function _show_url_for() {
    error "not implemented"
}

function _goto() {
    error "not implemented"
}

is_help_mode "${@}" && return

case ${1} in
    goto)
        _goto ${2}
    ;;
    all)
        _show_all
    ;;
    show)
        _show_url_for ${2}
    ;;
    *)
        _show_url_for ${1}
    ;;
esac