#!/usr/bin/env bash
# vim: ft=sh

SUBCOMMAND_DESC="List relevant URLs"
SUBCOMMAND_HELP=$(cat <<EOH

all             List all URLs and aliases.

goto [ALIAS]    Will trigger 'open URL', in OSX this
                will fire up your browser.

show [ALIAS]    List URL for an specific [ALIAS].

[ALIAS]         Just a shortcut. Same as 'show [ALIAS]'.

EOH
)

declare -A "list"
list[dev]='http://localhost:3000'
list[prod]='http://www.transervicos.org/'
list[ci]='https://gitlab.com/juuh42dias/transervicos/pipelines'

function _show_all() {
    # you probably would like to loop into the URLs list above and printf each URL in there
    error "not implemented"
}

function _show_url_for() {
    # you probably would like to printf a specific URL from that previous list searching by its alias
    error "not implemented"
}

function _goto() {
    # if you type: open 'http://www.google.com.br' on your terminal it will open google on your browser
    error "not implemented"
}

is_help_mode "${@}" && return

case ${1} in
    goto)
        _goto ${2}
    ;;
    all)
        _show_all
    ;;
    show)
        _show_url_for ${2}
    ;;
    *)
        _show_url_for ${1}
    ;;
esac